version: '3'
services:
  app:
    build: .
    volumes:
      - .:/home/app
    environment:
      RAILS_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - postgres    
  postgres:
    image: postgres:9.4
    ports:
      - "5432"
