angular.module('neighborhoodstat').run(($rootScope) ->
  $rootScope.flash = {}
  $rootScope.flash.text = ''
  $rootScope.flash.type = ''
  $rootScope.flash.timeout = 5000
  $rootScope.hasFlash = false
  return
).directive('dynamic', ($compile) ->
  {
    restrict: 'A'
    replace: true
    link: (scope, ele, attrs) ->
      scope.$watch attrs.dynamic, (html) ->
        ele.html html
        $compile(ele.contents()) scope
        return
      return

  }
).directive('closeFlash', ($compile, Flash) ->
  { link: (scope, ele) ->
    ele.on 'click', ->
      Flash.dismiss()
      return
    return
 }
).directive('flashMessage', ($compile, $rootScope) ->
  {
    restrict: 'A'
    template: '<div role="alert" ng-show="hasFlash" class="alert {{flash.addClass}} alert-{{flash.type}} alert-dismissible ng-hide alertIn alertOut "> <span dynamic="flash.text"></span> <button type="button" class="close" close-flash><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button> </div>'
    link: (scope, ele, attrs) ->
      # get timeout value from directive attribute and set to flash timeout
      $rootScope.flash.timeout = parseInt(attrs.flashMessage, 10)
      return

  }
).factory 'Flash', [
  '$rootScope'
  '$timeout'
  ($rootScope, $timeout) ->
    dataFactory = {}
    timeOut = undefined
    # Create flash message

    dataFactory.create = (type, text, addClass) ->
      $this = this
      $timeout.cancel timeOut
      $rootScope.flash.type = type
      $rootScope.flash.text = text
      $rootScope.flash.addClass = addClass
      $timeout (->
        $rootScope.hasFlash = true
        return
      ), 100
      timeOut = $timeout((->
        $this.dismiss()
        return
      ), $rootScope.flash.timeout)
      return

    # Cancel flashmessage timeout function

    dataFactory.pause = ->
      $timeout.cancel timeOut
      return

    # Dismiss flash message

    dataFactory.dismiss = ->
      $timeout.cancel timeOut
      $timeout ->
        $rootScope.hasFlash = false
        return
      return

    dataFactory
]

# ---
# generated by js2coffee 2.2.0