# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1ef93666f35ce14c37fc3a64eabef5896d08b6a2a2ac967542c529c8304fb20aec5e45a101b1971fad556b251eeefa7e7f4f2ee9483181535aaa2b2b7a5726

test:
  secret_key_base: aafe1498df05dabff8bb2c71f7cab9a808117767f8153b30f11eaf81c05fcbe20af97feda366afe281e570846e2e74dc27d6c60116738c5597779fbfc47d3057

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
