module Crime
  class CodeMapper
    ASSAULT = 1300
    HOMICIDE = 0900
    SEX_OFFENSE_FORCIBLE =
    SEX_OFFENSE_NONFORCIBLE =

    ARSON
    BAD_CHECKS
    BURGLARY
    COUNTERFEITING
    EMBEZZLEMENT
    EXTORTION
    FRAUD
    MOTOR_VEHICLE_THEFT
    ROBBERY
    STOLEN_PROPERTY
    THEFT
    VANDALISM

    CURFEW
    DISORDERLY_CONDUCT
    DRUG_NARCOTIC
    DUI
    DRUNKENNESS
    DOMESTIC_NONVIOLENT
    GAMBLING
    PORNOGRAPHY
    PROSTITUTION
    LIQUOR_LAW_VIOLATION
    PEEPING_TOMS
    TRESPASSING
  end
end